"""
Django settings for pledge_manager project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h&r8+lkf(wmru=8&3ik(&)yfma%ye28@&m)2n+1m=0f*4n+b#+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'pledges',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pledge_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pledge_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files for user uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files directories
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SMS Configuration
NOTIFY_AFRICA_API_TOKEN = "ntfy_ad924345606e93882ad77ed1aae06a4b1054e687920c4b437c6bad1fc3e6d8eb"  # Replace with your actual API token
NOTIFY_AFRICA_SENDER_ID = "253"  # Replace with your sender ID

# WhatsApp Configuration  
WHATSAPP_API_TOKEN = "EAAQiTIkQL2MBQgYXGjMZCJrg78DWP5vhGb6f3ST0n6cgP67muKVZBYsUiYxEEK60yrZC8WXa4IPHxZBePKnw7fTCq4oesAaZBtpxXEJeoxPNuabVTksZCdIsecUUAK61ZAm5rIdZBWGP8q3ZBkt7T55KwtbjjJiQpX8fZA3ddVyZC2kIo7yb0Pzw10TwIWZC8sRuODLgjeZAB24nsqfeRRN6cG0ceE2XX7yfHUiWcM6jh"  # Replace with your Meta Business API token
WHATSAPP_PHONE_NUMBER_ID = "834398519761412"  # Replace with your WhatsApp Business phone number ID
WHATSAPP_TEMPLATE_NAME = "kadi_mualiko"  # Template name

# Base URL Configuration
BASE_URL = "http://127.0.0.1:8000"  # Change to your production domain (e.g., "https://yourdomain.com")

# Login settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

SMS_DEFAULT_MESSAGE = """Habari {name},

Unakaribishwa kwenye harusi ya Stanslaus Kayombo & Felista Malibate

Tarehe: 14-Feb-2026
Misa: Kanisa Katoliki la Mt. Dominico, Mbezi Makonde saa nane mchana

Ukumbi: Masiani Hall, Mbezi Chini, Bararabara ya Mwai Kibaki, karibu na kituo cha mafuta cha Engen, Mtaa Kilimani Close, 12:00 Jioni.

Kadi: {card_code} | {card_capacity}

Onyesha meseji hii ukumbini.

Kwa mawasiliano, 0699503737; 0767471491; 0743434373
"""

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'pledge_manager.log',
            'formatter': 'verbose',
        },
        'sms_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'sms_logs.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'pledges.sms_utils': {
            'handlers': ['sms_file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'pledges': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
