# Generated by Django 6.0.2 on 2026-02-11 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(help_text='Mobile number (Unique)', max_length=15, unique=True)),
                ('name', models.CharField(help_text="Person's name", max_length=255)),
                ('pledge', models.DecimalField(decimal_places=2, default=0, help_text='Pledged amount', max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid', max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount', max_digits=10)),
                ('card_capacity', models.IntegerField(default=0, help_text='Card capacity (0, 1, or 2 based on paid amount)')),
                ('card_code', models.CharField(blank=True, default='', help_text='Unique 3-letter card identification code', max_length=3, null=True, unique=True)),
                ('normal_message_sent', models.BooleanField(default=False, help_text='Normal message sent status')),
                ('whatsapp_sent', models.BooleanField(default=False, help_text='WhatsApp message sent status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pledge Record',
                'verbose_name_plural': 'Pledge Records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('total_records', models.IntegerField(default=0)),
                ('new_records', models.IntegerField(default=0)),
                ('updated_records', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True, help_text='Any errors during upload')),
            ],
            options={
                'verbose_name': 'Upload Log',
                'verbose_name_plural': 'Upload Logs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
