# Generated by Django 6.0.2 on 2026-02-11 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(help_text='Content of the SMS message')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('message_id', models.CharField(blank=True, help_text='SMS provider message ID', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
                ('message_type', models.CharField(default='wedding_invitation', help_text='Type of message', max_length=50)),
                ('pledge_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='pledges.pledgerecord')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ['-sent_at'],
            },
        ),
    ]
