# Generated by Django 6.0.2 on 2026-02-11 10:10

from django.db import migrations, models


def populate_recipient_fields(apps, schema_editor):
    """
    Populate recipient fields with data from pledge_record for existing SMS messages
    """
    SMSMessage = apps.get_model('pledges', 'SMSMessage')
    for sms in SMSMessage.objects.all():
        sms.recipient_name = sms.pledge_record.name
        sms.recipient_mobile = sms.pledge_record.mobile_number
        sms.save()


def reverse_populate_recipient_fields(apps, schema_editor):
    """
    Reverse migration - no action needed since we're removing fields
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0002_smsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='recipient_name',
            field=models.CharField(default='Unknown', help_text='Name of the SMS recipient', max_length=255),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='recipient_mobile',
            field=models.CharField(default='000000000', help_text='Mobile number of the SMS recipient', max_length=15),
        ),
        migrations.RunPython(populate_recipient_fields, reverse_populate_recipient_fields),
    ]
