# Generated by Django 5.1.5 on 2026-02-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0003_add_recipient_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgerecord',
            name='invitation_image_url',
            field=models.URLField(blank=True, help_text='URL of the generated invitation image', null=True),
        ),
    ]
