# Generated by Django 5.1.5 on 2026-02-12 11:00

from django.db import migrations
from django.contrib.auth.models import User


def create_login_user(apps, schema_editor):
    """Create the default login user"""
    username = 'mubote'
    password = 'kayombo'
    
    # Delete existing user if it exists
    if User.objects.filter(username=username).exists():
        User.objects.filter(username=username).delete()
    
    # Create new user
    User.objects.create_user(
        username=username,
        password=password,
        is_staff=False,
        is_superuser=False
    )


def reverse_create_login_user(apps, schema_editor):
    """Remove the login user"""
    username = 'mubote'
    User.objects.filter(username=username).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0004_pledgerecord_invitation_image_url'),
    ]

    operations = [
        migrations.RunPython(create_login_user, reverse_create_login_user),
    ]
