# Generated by Django 5.1.5 on 2026-02-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0005_auto_20260212_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgerecord',
            name='attended_count',
            field=models.IntegerField(default=0, help_text='Number of people who attended'),
        ),
    ]
