# Generated by Django 5.1.5 on 2026-02-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0006_pledgerecord_attended_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgerecord',
            name='card_code',
            field=models.CharField(blank=True, default='', help_text='Unique card identification code', max_length=10, null=True, unique=True),
        ),
    ]
